# Generated by Django 5.2.1 on 2025-05-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnalite',
            name='pays_reference',
        ),
        migrations.RemoveField(
            model_name='personnalite',
            name='pays_saisie',
        ),
        migrations.AddField(
            model_name='personnalite',
            name='pays',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='firstapp.pays'),
        ),
    ]
